#!/bin/bash

URL=mysftp@192.168.66.136
TMPFILE=/root/script/test
KeyPath=/root/136k
space=""
tr="|"
echo 'ls -1l' > $TMPFILE

function handle_dir {
  #echo "====== $1 ========="
  local dir=$1
  sftp -b $TMPFILE -oIdentityFile=$KeyPath "$URL:$dir" | tail -n +2 | while read info; do
    echo " $2$tr  $dir ; $info" >> log_tmp
    if egrep -q '^d' <<< $info; then
       info=$(echo $info)
       subdir=$(cut -d ' ' -f9- <<< $info)
       tr="\\"
       space="`echo $2`|"
       handle_dir "$dir/$subdir" "$space"
    fi
    tr="|"
  done
}
cat log_tmp > log_tmp_old
>log_tmp
echo "-----------------------------------------------------------------------------------------`date`---------------------------------------------------------------------------------------" >> log
handle_dir "." $space

#cat log_tmp| sort -t '|' -k 1 >> log
cat log_tmp >> log
echo "----------------------------------------now------------------------------------------------------ diff ------------------------------------------------before----------------------------------------" >> log
sed -i 's/\\//g;s/|//g' log_tmp
sed -i 's/\\//g;s/|//g' log_tmp_old
diff -b -y -W 200 --suppress-common-lines log_tmp log_tmp_old  >> log 
echo "------------------------------------------------------------------------------------------------- end ----------------------------------------------------------------------------------------------" >> log
